language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-0
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - xvfb-run julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
jobs:
  include:
    - stage: Documentation
      julia: 1.0
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
